//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HARSHANA-PC\\SQLEXPRESS;Initial Catalog=ERP_NEW_Mag;Persist Security I" +
            "nfo=True;User ID=sa;Password=hhh")]
        public string ERP_NEW_MagConnectionString {
            get {
                return ((string)(this["ERP_NEW_MagConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HARSHANA-PC\\SQLEXPRESS;Initial Catalog=ERPAvansmart;User ID=sa;Passwo" +
            "rd=hhh;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string ERPAvansmartConnectionString {
            get {
                return ((string)(this["ERPAvansmartConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NUWAN-PC\\SQLEXPRESS;Initial Catalog=ERP_Dinemore;Persist Security Inf" +
            "o=True;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework" +
            "")]
        public string ERP_DinemoreConnectionString {
            get {
                return ((string)(this["ERP_DinemoreConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHANAKA-LAP\\SQLEXPRESS;Initial Catalog=Lakpohora_Source;Persist Secur" +
            "ity Info=True;User ID=sa;Password=victory@123;MultipleActiveResultSets=True;Appl" +
            "ication Name=EntityFramework")]
        public string Lakpohora_SourceConnectionString {
            get {
                return ((string)(this["Lakpohora_SourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KASUN\\SQLEXPRESS;Initial Catalog=Lakpohora_ERP;Persist Security Info=" +
            "True;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string Lakpohora_ERPConnectionString {
            get {
                return ((string)(this["Lakpohora_ERPConnectionString"]));
            }
        }
    }
}
